export type Lang = "ar" | "en";

export const content = {
  ar: {
    dir: "rtl" as const,
    langLabel: "EN",
    topBar: "🔔 إطلاق جديد — سيلفر ووك & سيلفر باي · وحدات محدودة جدًا · مقدم 5% فقط",
    nav: { register: "سجّل اهتمامك", call: "اتصل الآن", whatsapp: "واتساب" },
    hero: {
      eyebrow: "مشروع أورا للتطوير العقاري · سيدي حنيش، الساحل الشمالي",
      title1: "سيلفر ساندس الساحل الشمالي",
      title2: "الإطلاق الجديد: سيلفر ووك & سيلفر باي",
      sub: "أحدث الأسعار والتوافر بيتأكدوا عند الاستفسار — اعرف خطط السداد وأنواع الوحدات وكل تفاصيل المشروع بخطوات واضحة، وتشطيب كامل بالتكييفات بمقدم 5% وتقسيط حتى 8 سنوات.",
      badges: ["تحديثات التوافر أولًا بأول", "أسعار محدثة عند الاستفسار"],
      cta: "سجّل استفسارك",
      ctaGhost: "اطلب أحدث الأسعار",
      ctaWa: "واتساب",
      trust: "منصة معلومات واستفسارات مستقلة · يتواصل معك فريق مبيعات معتمد بأسعار المطور الرسمية بدون أي رسوم",
    },
    heroForm: {
      title: "احصل على الأسعار والماستر بلان",
      sub: "سجّل بياناتك وهنتواصل معاك في نفس اليوم",
    },
    marquee: [
      "بروميناد على الميّه", "كافيهات ومطاعم", "شاطئ رملي خاص", "لاجونز كريستالية",
      "تشطيب كامل + تكييف", "مقدم 5%", "تقسيط 8 سنوات", "فندق 5 نجوم", "جيم وسبا",
    ],
    stats: [
      { value: "+500", label: "فدان مساحة الوجهة" },
      { value: "1.2 كم", label: "واجهة شاطئية" },
      { value: "200 م", label: "بروميناد تجاري في سيلفر ووك" },
      { value: "+10 مليار", label: "جنيه حجم الاستثمارات" },
    ],
    about: {
      eyebrow: "الوجهة",
      title: "سيلفر ساندس.. الكاريبي على شواطئ سيدي حنيش",
      body: "على أنقى مياه في الساحل الشمالي، طوّرت أورا العقارية بقيادة المهندس نجيب ساويرس وجهة متكاملة صممتها WATG — واحدة من أعرق شركات تصميم المنتجعات في العالم — بطراز مستوحى من العمارة الكاريبية وألوان المتوسط.",
      body2: "سيلفر ساندس مش قرية مصيفية موسمية. هي امتداد لفلسفة أورا في الجونة: داون تاون حي بيعيش طول السنة، بمرافق كاملة من مركز طبي وفنادق بوتيك و4 كلوب هاوس وهب تجاري 6,000 م² — وده اللي بيخليها من أقوى فرص الاستثمار في الساحل مش بس مكان للمصيف.",
      cta: "اعرف أسعار الإطلاق",
    },
    location: {
      eyebrow: "الموقع",
      title: "الكيلو 247 الطريق الساحلي الدولي · سيدي حنيش",
      body: "في قلب أنقى منطقة في الساحل الشمالي، وعلى دقائق من أهم المحاور والوجهات:",
      points: [
        { place: "ألماظة باي", dist: "4 كم" },
        { place: "طريق الفوكة", dist: "دقائق" },
        { place: "رأس الحكمة", dist: "23 كم" },
        { place: "مطار مرسى مطروح", dist: "50 دقيقة" },
        { place: "العلمين", dist: "138 كم" },
        { place: "القاهرة", dist: "360 كم" },
      ],
      cta: "اسأل عن الموقع بالتفصيل",
    },
    launch: {
      eyebrow: "الإطلاق الجديد",
      title: "سيلفر ووك & سيلفر باي",
      body: "لأول مرة داخل سيلفر ساندس: وحدات مرفوعة فوق بروميناد حي على اللاجون مباشرة — كافيهات ومطاعم ومحلات تحتك، وشاطئ رملي وميّه كريستالية قدامك. خصوصية كاملة فوق، وحياة كاملة تحت. نفس تجربة داون تاون الجونة.. بس على لاجون الساحل.",
      features: [
        { icon: "🌊", title: "لاجون رملي تسبح فيه", desc: "لاجون سبّاح بشاطئ رملي وبيتش زون خاصة بمقاعد مظللة" },
        { icon: "☕", title: "بروميناد تجاري 200 متر", desc: "كافيهات ومطاعم على الواجهة المائية بتعيش نهارًا وليلًا تحت وحدتك" },
        { icon: "❄️", title: "استلام فندقي", desc: "تشطيب سوبر لوكس كامل + تكييفات — جاهزة للسكن أو التأجير" },
        { icon: "⏳", title: "وحدات محدودة جدًا", desc: "المرحلة الأولى من الإطلاق بعدد وحدات محدود وأولوية للحجز المبكر" },
      ],
    },
    units: {
      eyebrow: "الوحدات والأسعار",
      title: "اختار عنوانك على الميّه",
      note: "الأسعار استرشادية من آخر إطلاق وقابلة للتغيير من المطور — والإطلاق يشمل كمان كبائن ولودجز بمساحات مختلفة. سجّل للحصول على قائمة الأسعار الرسمية الكاملة اليوم.",
      priceLabel: "السعر يبدأ من",
      cta: "اعرف التفاصيل والسعر النهائي",
      cards: [
        {
          type: "شقة غرفة نوم",
          area: "68 م²",
          tag: "الأنسب للاستثمار",
          features: ["تراس بإطلالة على اللاجون", "عائد إيجاري فندقي مرتفع", "أقل مقدم للدخول"],
          price: "8.9 مليون جنيه",
        },
        {
          type: "شقة غرفتين نوم",
          area: "95 م²",
          tag: "الأكثر طلبًا",
          features: ["ماستر سويت + معيشة مفتوحة", "تراس على البروميناد", "توازن مثالي: مصيف واستثمار"],
          price: "13.2 مليون جنيه",
        },
        {
          type: "شقة 3 غرف نوم",
          area: "134 م²",
          tag: "للعائلات",
          features: ["معيشة عائلية واسعة", "غرفة خادمة", "تراس بانورامي على اللاجون"],
          price: "22.97 مليون جنيه",
        },
      ],
    },
    amenities: {
      eyebrow: "مرافق المدينة الكاملة",
      title: "كل حاجة محتاجها.. جوه السور",
      items: [
        { icon: "🏥", label: "مركز طبي متكامل" },
        { icon: "🏨", label: "فنادق بوتيك فاخرة" },
        { icon: "🛍️", label: "هب تجاري 6,000 م²" },
        { icon: "🏛️", label: "4 كلوب هاوس" },
        { icon: "🎬", label: "سينما مكشوفة" },
        { icon: "👨‍👩‍👧", label: "كيدز إيريا" },
        { icon: "🌊", label: "لاجونز سبّاحة 88 ألف م²" },
        { icon: "🏖️", label: "شاطئ خاص 1.2 كم" },
      ],
    },
    payment: {
      eyebrow: "خطة السداد",
      title: "تملّك بأقل مقدم في الساحل",
      items: [
        { value: "5%", label: "مقدم تعاقد", desc: "والباقي مقسط بالكامل بدون فوائد" },
        { value: "8", label: "سنوات سداد", desc: "أقساط مريحة وممتدة" },
        { value: "5%", label: "جدية حجز EOI", desc: "تضمن أولويتك في اختيار الوحدة" },
      ],
      cta: "احسب قسطك مع مستشار المبيعات",
    },
    developer: {
      eyebrow: "المطوّر",
      title: "أورا.. توقيع نجيب ساويرس",
      body: "أورا للتطوير العقاري — بقيادة المهندس نجيب ساويرس — من أقوى شركات التطوير في مصر والمنطقة، بمحفظة مشروعات عالمية في مصر والإمارات وقبرص وجرينادا وباكستان. باستثمارات تتجاوز 10 مليارات جنيه في سيلفر ساندس وحدها، وخبرة صنعت أنجح داون تاون ساحلي في مصر: الجونة.",
      projects: ["زد الشيخ زايد", "زد إيست القاهرة الجديدة", "سولانا زايد الجديدة", "بيراميد هيلز", "دوليًا: الإمارات · قبرص · جرينادا · باكستان"],
      badge: "خبرة الجونة.. في الساحل",
    },
    why: {
      eyebrow: "ليه تحجز معانا؟",
      title: "فريق مبيعات معتمد.. بدون أي تكلفة إضافية",
      items: [
        { icon: "✅", title: "أسعار المطور الرسمية", desc: "نفس قائمة أسعار أورا بالظبط — صفر عمولة وصفر رسوم عليك كعميل." },
        { icon: "⚡", title: "أولوية اختيار الوحدات", desc: "الوحدات محدودة — التسجيل المبكر يضمنلك أولوية اختيار الدور والإطلالة." },
        { icon: "🎯", title: "استشارة قبل القرار", desc: "مقارنة محايدة بين الوحدات والمراحل وتحليل العائد الاستثماري المتوقع." },
        { icon: "🤝", title: "معاك للاستلام", desc: "متابعة كاملة من الحجز للتعاقد للاستلام — إنت بس اختار وحدتك." },
      ],
    },
    faq: {
      eyebrow: "أسئلة شائعة",
      title: "كل اللي محتاج تعرفه",
      items: [
        { q: "إيه الفرق بين سيلفر ووك وسيلفر باي؟", a: "الاتنين أحدث إطلاق داخل سيلفر ساندس على اللاجون: سيلفر ووك وحدات (شقق وكبائن ولودجز) مرفوعة فوق البروميناد التجاري مباشرة، وسيلفر باي شاليهات على الواجهة المائية. الاتنين بتشطيب كامل وتكييفات ونفس خطة السداد." },
        { q: "الأسعار بتبدأ من كام؟", a: "آخر أسعار معلنة بدأت من حوالي 8.9 مليون جنيه لوحدة الغرفة الواحدة. الأسعار استرشادية وبتتغير مع كل مرحلة — سجّل وهنبعتلك قائمة الأسعار الرسمية المحدثة النهاردة." },
        { q: "إيه نظام السداد؟", a: "مقدم تعاقد 5% فقط والباقي على 8 سنوات، مع جدية حجز (EOI) 5% بتضمن أولويتك في اختيار الوحدة يوم الإطلاق." },
        { q: "الوحدات متشطبة؟", a: "أيوه — كل الوحدات بتتسلم تشطيب سوبر لوكس كامل شامل التكييفات (من غير حوامل المطبخ)، جاهزة للسكن أو التأجير الفندقي. وده معيار تسليم أورا نفسه في كل مراحل سيلفر ساندس." },
        { q: "المشروع فين بالظبط؟", a: "سيلفر ساندس في سيدي حنيش عند الكيلو 247 على الطريق الساحلي الدولي (إسكندرية–مطروح)، بين هاسيندا حنيش وألماظة باي مباشرة، وعلى 23 كم من رأس الحكمة مع وصول سهل من طريق الفوكة." },
        { q: "هل في رسوم لما أحجز عن طريقكم؟", a: "إطلاقًا. إحنا فريق مبيعات معتمد بنتقاضى عمولتنا من المطور مباشرة — إنت بتدفع نفس سعر أورا الرسمي بالظبط، وبتاخد فوقه استشارة وأولوية حجز." },
      ],
    },
    form: {
      eyebrow: "سجّل اهتمامك",
      title: "سيب بياناتك.. وهنرجعلك بالأسعار الرسمية والماستر بلان",
      sub: "بنرد في نفس يوم التسجيل — وأولوية المكالمات للتسجيل الأول",
      name: "الاسم بالكامل",
      phone: "رقم الموبايل / واتساب",
      email: "البريد الإلكتروني (اختياري)",
      unit: "الوحدة اللي تهمك",
      unitOptions: ["لسه محددتش", "غرفة نوم · 68 م²", "غرفتين نوم · 95 م²", "3 غرف نوم · 134 م²"],
      buyer: "الغرض",
      buyerOptions: ["مصيف شخصي", "استثمار", "الاتنين"],
      submit: "اطلب مكالمة الآن — مجانًا",
      submitting: "جاري الإرسال...",
      disclosure: "هذه منصة معلومات واستفسارات مستقلة. بالضغط على الإرسال، أنت توافق على تواصل فريق مبيعات معتمد ومستقل معك بخصوص المشروع. الأسعار استرشادية وقابلة للتغيير.",
      error: "حصلت مشكلة في الإرسال — جرّب تاني أو كلمنا واتساب مباشرة.",
    },
    popup: {
      title: "متفوتش أسعار الإطلاق",
      body: "الوحدات محدودة جدًا والأولوية للتسجيل المبكر. سيب رقمك وهنبعتلك قائمة الأسعار الرسمية دلوقتي.",
      cta: "ابعتلي الأسعار",
      close: "لاحقًا",
    },
    sticky: { call: "اتصال", wa: "واتساب", form: "الأسعار" },
    floating: { wa: "كلمنا واتساب", call: "اتصل الآن" },
    footer: {
      about: "سيلفر ووك & سيلفر باي — أحدث إطلاق على اللاجون داخل سيلفر ساندس الساحل الشمالي، تطوير أورا العقارية.",
      linksTitle: "روابط",
      links: [
        { href: "/about", label: "من نحن" },
        { href: "/privacy", label: "سياسة الخصوصية" },
        { href: "/disclaimer", label: "إخلاء المسؤولية" },
      ],
      contactTitle: "تواصل معنا",
      location: "سيدي حنيش · كم 247 الطريق الساحلي الدولي",
      disclaimer: "إخلاء مسؤولية: هذه منصة معلومات واستفسارات مستقلة منشورة بواسطة فريق مبيعات عقاري معتمد ومستقل، وهي ليست الموقع الرسمي لشركة أورا للتطوير العقاري أو مشروع سيلفر ساندس. جميع العلامات التجارية وأسماء المشاريع والصور ملك لأصحابها وتُستخدم لأغراض التسويق والترشيح فقط. الأسعار والمساحات وخطط السداد استرشادية ومقدمة من المطور وقابلة للتغيير دون إشعار مسبق، ولا تُعد عرضًا تعاقديًا.",
      rights: "جميع الحقوق محفوظة. سيلفر ساندس مشروع تطوير أورا.",
    },
    cookie: { text: "بنستخدم كوكيز لتحسين تجربتك وقياس أداء الحملات.", accept: "موافق" },
  },

  en: {
    dir: "ltr" as const,
    langLabel: "عربي",
    topBar: "🔔 New Launch — Silver Walk & Silver Bay · Very limited units · Only 5% down",
    nav: { register: "Register Interest", call: "Call Now", whatsapp: "WhatsApp" },
    hero: {
      eyebrow: "By ORA Developers · Sidi Heneish, North Coast",
      title1: "Silversands North Coast",
      title2: "New launch: Silver Walk & Silver Bay",
      sub: "Latest availability and latest prices confirmed upon inquiry — explore payment plans, unit types, and project details with clear next steps. Fully finished with ACs, 5% down over 8 years.",
      badges: ["Latest availability updates", "Latest prices upon inquiry"],
      cta: "Send Inquiry",
      ctaGhost: "Request Latest Prices",
      ctaWa: "WhatsApp",
      trust: "Independent information & inquiries platform · An authorized sales team contacts you with official developer pricing at zero fees",
    },
    heroForm: {
      title: "Get prices & the masterplan",
      sub: "Leave your details — we reply the same day",
    },
    marquee: [
      "Waterfront promenade", "Cafés & restaurants", "Private sandy beach", "Crystal lagoons",
      "Fully finished + ACs", "5% down payment", "8-year plan", "5-star hotel", "Gym & spa",
    ],
    stats: [
      { value: "500+", label: "Feddans of destination" },
      { value: "1.2 km", label: "Beachfront" },
      { value: "200 m", label: "Retail promenade at Silver Walk" },
      { value: "EGP 10bn+", label: "Total investments" },
    ],
    about: {
      eyebrow: "The Destination",
      title: "Silversands — the Caribbean on Sidi Heneish shores",
      body: "On the clearest waters of the North Coast, ORA Developers — led by Naguib Sawiris — built a complete destination masterplanned by WATG, one of the world's most celebrated resort design firms, in a style inspired by Caribbean architecture and Mediterranean color.",
      body2: "Silversands is not a seasonal village. It extends ORA's El Gouna philosophy: a living downtown that runs all year, with a medical center, boutique hotels, 4 clubhouses and a 6,000 sqm commercial hub — which is exactly what makes it one of the coast's strongest investments, not just a summer home.",
      cta: "Get launch prices",
    },
    location: {
      eyebrow: "Location",
      title: "KM 247, International Coastal Road · Sidi Heneish",
      body: "In the heart of the coast's purest stretch, minutes from every major axis and destination:",
      points: [
        { place: "Almaza Bay", dist: "4 km" },
        { place: "Fouka Road", dist: "Minutes" },
        { place: "Ras El Hekma", dist: "23 km" },
        { place: "Marsa Matrouh Airport", dist: "50 min" },
        { place: "El Alamein", dist: "138 km" },
        { place: "Cairo", dist: "360 km" },
      ],
      cta: "Ask about the location",
    },
    launch: {
      eyebrow: "The New Launch",
      title: "Silver Walk & Silver Bay",
      body: "For the first time at Silversands: residences elevated above a living lagoon-front promenade — cafés, restaurants and retail below, a sandy beach and crystal water ahead. Full privacy above, full life below. The downtown El Gouna experience — on the coast's lagoon.",
      features: [
        { icon: "🌊", title: "A swimmable sandy lagoon", desc: "Swim-ready lagoon with a private beach zone and shaded seating" },
        { icon: "☕", title: "A 200 m retail promenade", desc: "Waterfront cafés & restaurants alive day and night, right below" },
        { icon: "❄️", title: "Hotel-grade delivery", desc: "Fully finished with ACs — ready to live in or rent out" },
        { icon: "⏳", title: "Very limited units", desc: "A limited first release with priority for early registration" },
      ],
    },
    units: {
      eyebrow: "Residences & Prices",
      title: "Choose your address by the water",
      note: "Prices are indicative from the latest release and subject to change — the launch also includes cabanas and lodges in various sizes. Register for today's full official price list.",
      priceLabel: "Starting from",
      cta: "Get full details & final price",
      cards: [
        {
          type: "1-Bedroom Apartment", area: "68 sqm", tag: "Best for investment",
          features: ["Lagoon-view terrace", "High hospitality rental yield", "Lowest entry ticket"],
          price: "EGP 8.9M",
        },
        {
          type: "2-Bedroom Apartment", area: "95 sqm", tag: "Most requested",
          features: ["Master suite + open living", "Promenade terrace", "Perfect summer + investment balance"],
          price: "EGP 13.2M",
        },
        {
          type: "3-Bedroom Apartment", area: "134 sqm", tag: "For families",
          features: ["Wide family living", "Maid's room", "Panoramic lagoon terrace"],
          price: "EGP 22.97M",
        },
      ],
    },
    amenities: {
      eyebrow: "A complete town",
      title: "Everything you need, inside the gates",
      items: [
        { icon: "🏥", label: "Full medical center" },
        { icon: "🏨", label: "Boutique hotels" },
        { icon: "🛍️", label: "6,000 sqm commercial hub" },
        { icon: "🏛️", label: "4 clubhouses" },
        { icon: "🎬", label: "Open-air cinema" },
        { icon: "👨‍👩‍👧", label: "Kids area" },
        { icon: "🌊", label: "88K sqm swimmable lagoons" },
        { icon: "🏖️", label: "1.2 km private beach" },
      ],
    },
    payment: {
      eyebrow: "Payment Plan",
      title: "Own with the coast's lightest entry",
      items: [
        { value: "5%", label: "Down payment", desc: "Balance fully installed, interest-free" },
        { value: "8", label: "Years to pay", desc: "Comfortable extended instalments" },
        { value: "5%", label: "EOI", desc: "Secures your unit-selection priority" },
      ],
      cta: "Calculate your instalment with an advisor",
    },
    developer: {
      eyebrow: "The Developer",
      title: "ORA — signed by Naguib Sawiris",
      body: "ORA Developers — led by Naguib Sawiris — is one of the region's strongest developers, with a global portfolio spanning Egypt, the UAE, Cyprus, Grenada and Pakistan. With over EGP 10 billion invested in Silversands alone, and the track record that built Egypt's most successful coastal downtown: El Gouna.",
      projects: ["ZED Sheikh Zayed", "ZED East New Cairo", "Solana New Zayed", "Pyramid Hills", "International: UAE · Cyprus · Grenada · Pakistan"],
      badge: "El Gouna expertise — on the North Coast",
    },
    why: {
      eyebrow: "Why book with us?",
      title: "Authorized sales — at zero extra cost",
      items: [
        { icon: "✅", title: "Official developer pricing", desc: "The exact ORA price list — zero commission, zero fees charged to you." },
        { icon: "⚡", title: "Priority unit selection", desc: "Units are limited — early registration secures floor and view priority." },
        { icon: "🎯", title: "Advice before you decide", desc: "Neutral unit and phase comparison plus expected ROI analysis." },
        { icon: "🤝", title: "With you to handover", desc: "Full follow-up from booking to contract to delivery — you just choose." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Everything you need to know",
      items: [
        { q: "What's the difference between Silver Walk and Silver Bay?", a: "Both are the newest lagoon-front launch within Silversands: Silver Walk offers apartments, cabanas and lodges elevated directly above the commercial promenade, while Silver Bay offers waterfront chalets. Both are delivered fully finished with ACs on the same payment plan." },
        { q: "What do prices start from?", a: "The latest announced prices started from around EGP 8.9M for the 1-bedroom unit. Prices are indicative and change with each phase — register and we'll send today's official price list." },
        { q: "What's the payment plan?", a: "Just 5% down with the balance over 8 years, plus a 5% EOI that secures your unit-selection priority on launch day." },
        { q: "Are units finished?", a: "Yes — all units are delivered fully finished including air conditioning (without kitchen cabinets), ready for living or hospitality rental. That is ORA's own delivery standard across all Silversands phases." },
        { q: "Where exactly is the project?", a: "Silversands sits in Sidi Heneish at KM 247 on the International Coastal Road, directly between Hacienda Heneish and Almaza Bay, 23 km from Ras El Hekma with easy access via Fouka Road." },
        { q: "Do I pay any fees booking through you?", a: "None at all. We're an authorized sales team paid directly by the developer — you pay the exact official ORA price, and get advice plus booking priority on top." },
      ],
    },
    form: {
      eyebrow: "Register Your Interest",
      title: "Leave your details — we'll return with official prices & the masterplan",
      sub: "We reply the same day — call priority goes to the earliest registrations",
      name: "Full name",
      phone: "Phone / WhatsApp",
      email: "Email (optional)",
      unit: "Unit of interest",
      unitOptions: ["Not sure yet", "1 Bedroom · 68 sqm", "2 Bedroom · 95 sqm", "3 Bedroom · 134 sqm"],
      buyer: "Buyer type",
      buyerOptions: ["Personal use", "Investment", "Both"],
      submit: "Request my free callback",
      submitting: "Sending...",
      disclosure: "This is an independent information & inquiries platform. By submitting, you agree to be contacted by an independent authorized sales team about this project. Prices are indicative and subject to change.",
      error: "Something went wrong — try again or reach us on WhatsApp.",
    },
    popup: {
      title: "Don't miss launch pricing",
      body: "Units are very limited and priority goes to early registration. Leave your number and we'll send the official price list now.",
      cta: "Send me the prices",
      close: "Later",
    },
    sticky: { call: "Call", wa: "WhatsApp", form: "Prices" },
    floating: { wa: "WhatsApp us", call: "Call now" },
    footer: {
      about: "Silver Walk & Silver Bay — the newest lagoon-front launch within Silversands North Coast, developed by ORA.",
      linksTitle: "Links",
      links: [
        { href: "/about", label: "About Us" },
        { href: "/privacy", label: "Privacy Policy" },
        { href: "/disclaimer", label: "Disclaimer" },
      ],
      contactTitle: "Contact",
      location: "Sidi Heneish · KM 247 International Coastal Rd",
      disclaimer: "Disclaimer: This is an independent information & inquiries platform published by an independent, authorized real-estate sales team and is not the official website of ORA Developers or Silversands North Coast. All trademarks, project names and imagery belong to their respective owners and are used for marketing and referral purposes only. Prices, areas and payment terms are indicative, provided by the developer, and subject to change without notice. This is not a contractual offer.",
      rights: "All rights reserved. Silversands is a development by ORA.",
    },
    cookie: { text: "We use cookies to improve your experience and measure campaigns.", accept: "Accept" },
  },
};
